name: Check Daily Run

on:
  schedule:
    - cron: '*/15 * * * *'
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  ubuntu-run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Print event
        run: |
          echo "event=${{ github.event_name }}"
